# lextab.py. This file automatically created by PLY (version 3.11). Don't edit!
_tabversion   = '3.10'
_lextokens    = set(('ACCELERATOR', 'AREA_LIGHT_SOURCE', 'ATTRIBUTE_BEGIN', 'ATTRIBUTE_END', 'CAMERA', 'COMMENT', 'CONCAT_TRANSFORM', 'COORDINATE_SYSTEM', 'COORDINATE_SYSTEM_TRANSFORM', 'FILM', 'FILTER', 'IDENTITY', 'INCLUDE', 'INTEGRATOR', 'LIGHT_SOURCE', 'LIST', 'LOOKAT', 'MAKE_NAMED_MATERIAL', 'MATERIAL', 'NAMED_MATERIAL', 'NUMBER', 'OBJECT_BEGIN', 'OBJECT_END', 'OBJECT_INSTANCE', 'REVERSE_ORIENTATION', 'ROTATE', 'SAMPLER', 'SCALE', 'SHAPE', 'STRING', 'TEXTURE', 'TRANSFORM', 'TRANSFORM_BEGIN', 'TRANSFORM_END', 'TRANSLATE', 'WORLD_BEGIN', 'WORLD_END'))
_lexreflags   = 64
_lexliterals  = ''
_lexstateinfo = {'INITIAL': 'inclusive'}
_lexstatere   = {'INITIAL': [('(?P<t_STRING>"[^"]*")|(?P<t_NUMBER>[-+]?[0-9]*\\.?[0-9]+([eE][-+]?[0-9]+)?)|(?P<t_COMMENT>\\#.*)|(?P<t_newline>\\n+)|(?P<t_REVERSE_ORIENTATION>ReverseOrientation)|(?P<t_MAKE_NAMED_MATERIAL>MakeNamedMaterial)|(?P<t_COORDINATE_SYSTEM_TRANSFORM>CoordSysTransform)|(?P<t_COORDINATE_SYSTEM>CoordinateSystem)|(?P<t_AREA_LIGHT_SOURCE>AreaLightSource)|(?P<t_CONCAT_TRANSFORM>ConcatTransform)|(?P<t_ATTRIBUTE_BEGIN>AttributeBegin)|(?P<t_TRANSFORM_BEGIN>TransformBegin)|(?P<t_OBJECT_INSTANCE>ObjectInstance)|(?P<t_NAMED_MATERIAL>NamedMaterial)|(?P<t_ATTRIBUTE_END>AttributeEnd)|(?P<t_TRANSFORM_END>TransformEnd)|(?P<t_FILTER>PixelFilter)|(?P<t_ACCELERATOR>Accelerator)|(?P<t_OBJECT_BEGIN>ObjectBegin)|(?P<t_LIGHT_SOURCE>LightSource)|(?P<t_WORLD_BEGIN>WorldBegin)|(?P<t_INTEGRATOR>Integrator)|(?P<t_LIST>\\[[^\\]]*\\])|(?P<t_OBJECT_END>ObjectEnd)|(?P<t_TRANSLATE>Translate)|(?P<t_TRANSFORM>Transform)|(?P<t_WORLD_END>WorldEnd)|(?P<t_MATERIAL>Material)|(?P<t_IDENTITY>Identity)|(?P<t_SAMPLER>Sampler)|(?P<t_TEXTURE>Texture)|(?P<t_INCLUDE>Include)|(?P<t_CAMERA>Camera)|(?P<t_ROTATE>Rotate)|(?P<t_LOOKAT>LookAt)|(?P<t_SHAPE>Shape)|(?P<t_SCALE>Scale)|(?P<t_FILM>Film)', [None, ('t_STRING', 'STRING'), ('t_NUMBER', 'NUMBER'), None, ('t_COMMENT', 'COMMENT'), ('t_newline', 'newline'), (None, 'REVERSE_ORIENTATION'), (None, 'MAKE_NAMED_MATERIAL'), (None, 'COORDINATE_SYSTEM_TRANSFORM'), (None, 'COORDINATE_SYSTEM'), (None, 'AREA_LIGHT_SOURCE'), (None, 'CONCAT_TRANSFORM'), (None, 'ATTRIBUTE_BEGIN'), (None, 'TRANSFORM_BEGIN'), (None, 'OBJECT_INSTANCE'), (None, 'NAMED_MATERIAL'), (None, 'ATTRIBUTE_END'), (None, 'TRANSFORM_END'), (None, 'FILTER'), (None, 'ACCELERATOR'), (None, 'OBJECT_BEGIN'), (None, 'LIGHT_SOURCE'), (None, 'WORLD_BEGIN'), (None, 'INTEGRATOR'), (None, 'LIST'), (None, 'OBJECT_END'), (None, 'TRANSLATE'), (None, 'TRANSFORM'), (None, 'WORLD_END'), (None, 'MATERIAL'), (None, 'IDENTITY'), (None, 'SAMPLER'), (None, 'TEXTURE'), (None, 'INCLUDE'), (None, 'CAMERA'), (None, 'ROTATE'), (None, 'LOOKAT'), (None, 'SHAPE'), (None, 'SCALE'), (None, 'FILM')])]}
_lexstateignore = {'INITIAL': ' \t'}
_lexstateerrorf = {'INITIAL': 't_error'}
_lexstateeoff = {}
