// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_CONTIGUOUSALLOCATOR_PANDORA_SERIALIZATION_H_
#define FLATBUFFERS_GENERATED_CONTIGUOUSALLOCATOR_PANDORA_SERIALIZATION_H_

#include "flatbuffers/flatbuffers.h"

namespace pandora {
namespace serialization {

struct ContiguousAllocator;

struct ContiguousAllocator FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MAXSIZE = 4,
    VT_BLOCKSIZE = 6,
    VT_CURRENTSIZE = 8,
    VT_DATA = 10
  };
  uint32_t maxSize() const {
    return GetField<uint32_t>(VT_MAXSIZE, 0);
  }
  bool mutate_maxSize(uint32_t _maxSize) {
    return SetField<uint32_t>(VT_MAXSIZE, _maxSize, 0);
  }
  uint32_t blockSize() const {
    return GetField<uint32_t>(VT_BLOCKSIZE, 0);
  }
  bool mutate_blockSize(uint32_t _blockSize) {
    return SetField<uint32_t>(VT_BLOCKSIZE, _blockSize, 0);
  }
  uint32_t currentSize() const {
    return GetField<uint32_t>(VT_CURRENTSIZE, 0);
  }
  bool mutate_currentSize(uint32_t _currentSize) {
    return SetField<uint32_t>(VT_CURRENTSIZE, _currentSize, 0);
  }
  const flatbuffers::Vector<int8_t> *data() const {
    return GetPointer<const flatbuffers::Vector<int8_t> *>(VT_DATA);
  }
  flatbuffers::Vector<int8_t> *mutable_data() {
    return GetPointer<flatbuffers::Vector<int8_t> *>(VT_DATA);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_MAXSIZE) &&
           VerifyField<uint32_t>(verifier, VT_BLOCKSIZE) &&
           VerifyField<uint32_t>(verifier, VT_CURRENTSIZE) &&
           VerifyOffset(verifier, VT_DATA) &&
           verifier.VerifyVector(data()) &&
           verifier.EndTable();
  }
};

struct ContiguousAllocatorBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_maxSize(uint32_t maxSize) {
    fbb_.AddElement<uint32_t>(ContiguousAllocator::VT_MAXSIZE, maxSize, 0);
  }
  void add_blockSize(uint32_t blockSize) {
    fbb_.AddElement<uint32_t>(ContiguousAllocator::VT_BLOCKSIZE, blockSize, 0);
  }
  void add_currentSize(uint32_t currentSize) {
    fbb_.AddElement<uint32_t>(ContiguousAllocator::VT_CURRENTSIZE, currentSize, 0);
  }
  void add_data(flatbuffers::Offset<flatbuffers::Vector<int8_t>> data) {
    fbb_.AddOffset(ContiguousAllocator::VT_DATA, data);
  }
  explicit ContiguousAllocatorBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ContiguousAllocatorBuilder &operator=(const ContiguousAllocatorBuilder &);
  flatbuffers::Offset<ContiguousAllocator> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<ContiguousAllocator>(end);
    return o;
  }
};

inline flatbuffers::Offset<ContiguousAllocator> CreateContiguousAllocator(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t maxSize = 0,
    uint32_t blockSize = 0,
    uint32_t currentSize = 0,
    flatbuffers::Offset<flatbuffers::Vector<int8_t>> data = 0) {
  ContiguousAllocatorBuilder builder_(_fbb);
  builder_.add_data(data);
  builder_.add_currentSize(currentSize);
  builder_.add_blockSize(blockSize);
  builder_.add_maxSize(maxSize);
  return builder_.Finish();
}

inline flatbuffers::Offset<ContiguousAllocator> CreateContiguousAllocatorDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t maxSize = 0,
    uint32_t blockSize = 0,
    uint32_t currentSize = 0,
    const std::vector<int8_t> *data = nullptr) {
  auto data__ = data ? _fbb.CreateVector<int8_t>(*data) : 0;
  return pandora::serialization::CreateContiguousAllocator(
      _fbb,
      maxSize,
      blockSize,
      currentSize,
      data__);
}

}  // namespace serialization
}  // namespace pandora

#endif  // FLATBUFFERS_GENERATED_CONTIGUOUSALLOCATOR_PANDORA_SERIALIZATION_H_
